// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          role: 'admin' | 'member' | 'viewer'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          role?: 'admin' | 'member' | 'viewer'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          role?: 'admin' | 'member' | 'viewer'
          created_at?: string
          updated_at?: string
        }
      }
      roi_sessions: {
        Row: {
          id: string
          title: string
          company_name: string | null
          created_by: string
          data: Json
          is_archived: boolean
          is_favorite: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          company_name?: string | null
          created_by: string
          data?: Json
          is_archived?: boolean
          is_favorite?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          company_name?: string | null
          created_by?: string
          data?: Json
          is_archived?: boolean
          is_favorite?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      roi_versions: {
        Row: {
          id: string
          session_id: string
          version_number: number
          data: Json
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          version_number: number
          data: Json
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          version_number?: number
          data?: Json
          created_by?: string | null
          created_at?: string
        }
      }
      session_shares: {
        Row: {
          id: string
          session_id: string
          shared_with_user_id: string
          permission: 'read' | 'write'
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          shared_with_user_id: string
          permission?: 'read' | 'write'
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          shared_with_user_id?: string
          permission?: 'read' | 'write'
          created_at?: string
        }
      }
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          session_id: string | null
          action: 'view' | 'edit' | 'delete' | 'share' | 'create' | 'export'
          ip_address: string | null
          user_agent: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          session_id?: string | null
          action: 'view' | 'edit' | 'delete' | 'share' | 'create' | 'export'
          ip_address?: string | null
          user_agent?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          session_id?: string | null
          action?: 'view' | 'edit' | 'delete' | 'share' | 'create' | 'export'
          ip_address?: string | null
          user_agent?: string | null
          metadata?: Json | null
          created_at?: string
        }
      }
      login_attempts: {
        Row: {
          id: string
          identifier: string
          success: boolean
          attempted_at: string
          blocked_until: string | null
          user_agent: string | null
          ip_address: string | null
          created_at: string
        }
        Insert: {
          id?: string
          identifier: string
          success?: boolean
          attempted_at?: string
          blocked_until?: string | null
          user_agent?: string | null
          ip_address?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          identifier?: string
          success?: boolean
          attempted_at?: string
          blocked_until?: string | null
          user_agent?: string | null
          ip_address?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

